### ISSUE TITLE
RFC: Support singularity, runC

### ISSUE THREAD

**Issue by hexylena** [mulled/mulled#119]
Singularity was brought up by @moskalenko. 

Comparison of the two. https://groups.google.com/a/lbl.gov/forum/m/#!topic/singularity/-dl2i8vkGf8

All that would need to be done is an export from the built docker image to a singularity image. Shouldn't be too hard. :)

**Comment by thriqon** [comment]
You're talking about [gmkurtzer/singularity](https://github.com/gmkurtzer/singularity)?

I looked into it briefly... Is there any generally available host where we could upload the images to?

**Comment by bgruening** [comment]
We could at least offer an automatic conversions of Docker images to a Singularity one as part of involucro as a post-processing step.

**Comment by thriqon** [comment]
Sure, that's possible. But what shall be done with the finished image?

**Comment by bgruening** [comment]
I tend to use this tool and create simply tarball and save them on depot: https://github.com/singularityware/docker2singularity

Galaxy can then use these tarballs to run singularity.
