### ISSUE TITLE
can't access mulled

### ISSUE THREAD

**Issue by leipzig** [mulled/mulled#144]
I can't access `https://quay.io/mulled/samtools` only `mulled_dev`

```
docker run -it quay.io/mulled/samtools:1.3--1
Unable to find image 'quay.io/mulled/samtools:1.3--1' locally
Pulling repository quay.io/mulled/samtools
docker: Error: Status 403 trying to pull repository mulled/samtools: "{\"error\": \"Permission Denied (user: leipzig)\"}".
```

**Comment by bgruening** [comment]
@leipzig to join forces with other communities I decided to contribute all these containers to the biocontainers projects. So please try quay.io/biocontainers/samtools:1.3--1

**Comment by bgruening** [comment]
I need to update the readme, Oo.

**Comment by bgruening** [comment]
please have a look at auto-mulled for a more up-to-date readme file.
