### ISSUE TITLE
moving mulled completely to biocontainers

### ISSUE THREAD

**Issue by bgruening** [mulled/mulled#146]
Hi,

the biocontainer community is asking to move this repository under the biocontainers namespace. This is ok for me, but I think it will break the website or will need some work after the migration. Moreover, the biocontainer guys have there own website presenting containers from quay.io (http://biocontainers.pro/registry/).

So do we want to keep this website? Do we want to move the repo?
ping  @erasche @thriqon

**Comment by hexylena** [comment]
(No problem for me. Was never so involved in mulled. Was always a bit fond of mulled and the website, it was less generic than every other giant list of packages.)

**Comment by ypriverol** [comment]
Hi @erasche @bgruening the major idea is to reuse efforts and concentrate the work in one place. If you agree @erasche I can added you to the @biocontainers repository and we can implement some of the features into biocontainers tools. Happy to see this happening.

**Comment by thriqon** [comment]
Fine with me :)

**Comment by bgruening** [comment]
Done! Thanks everyone!
