### ISSUE TITLE
https://mulled.github.io/mulled/ from repo description not working?

### ISSUE THREAD

**Issue by mr-c** [mulled/mulled#147]

**Comment by bgruening** [comment]
Jupp, look at https://quay.io/organization/biocontainers
I removed the repo description. That was really long time ago. This repo is also not used anymore.

**Comment by mr-c** [comment]
Thanks. This repo is pinned at the top of the https://github.com/BioContainers organization, so that is a bit confusing. 

There's no link at https://quay.io/organization/biocontainers that explains who made it, what it is, and how it was made. Can you clarify?

Would be nice if the description or README of this repo provided the above answers as well

**Comment by bgruening** [comment]
Yeah, sorry, short on time ... maybe this helps you: http://biocontainers.pro/docs/101/intro/
